### ISSUE TITLE
Doesn't Work, On Windows 10?

### ISSUE THREAD

**Issue by Koolstr** [chrishelgert/zazu-fkill#15]
I tried using this plugin, but I cannot seem to get any process results to show. I type 'kill' or 'fkill', and the only thing which comes up in zazu are my fallback searches. Am I missing something? Fkill says it works on Windows as well, so this should work.

If there is a simple answer to this, then please update your documentation to give a more thorough and clearer depiction of what needs to be done to get it to work.

**Comment by chrishelgert** [comment]
I will look at it 👍🏻

**Comment by chrishelgert** [comment]
Hi @Koolstr thanks for your feedback,
I tried it today on a windows 10 laptop with the latest version of zazu and zazu-fkill and it worked.

Example: `kill fire` listed firefox as running process and i could kill it.

Can you give me some more information about your setup - or did you only type `kill` without a process / app name?

**Comment by Koolstr** [comment]
Thanks for looking into this.
I tried it in many ways, testing various processes and naming conventions. I've waited for maybe the search results to compile even. I still get absolutely nothing back. Perhaps I should be running Zazu with Administrator privileges?

I have a highly customized (read: pimped out) installation of Windows 10 Home, latest version - 1703 Build 15063.22. I wonder if all my mods have something to do with it? Maybe a conflicting app?

**Comment by Koolstr** [comment]
My bad, didn't mean to close XD

**Comment by chrishelgert** [comment]
mh mysterious.

I tested it on a standard windows 10 home  - also latest version, but without any mods.
I don´t know what mods you use or how they could conflict with the plugins i use.

This project uses [ps-list](https://github.com/sindresorhus/ps-list) for listing the processes and (fkill)[https://github.com/sindresorhus/fkill] for stopping them.

Maybe you could try the "usage" - example for [ps-list](https://github.com/sindresorhus/ps-list), if you get any results there?

**Comment by Koolstr** [comment]
(Sadly) I've never used npm yet. How exactly would I go about trying out the shown usage example?

**Comment by chrishelgert** [comment]
if you have node installed - you have also npm (if not you can download the latest version [here](https://nodejs.org/dist/v8.0.0/node-v8.0.0-x64.msi))

* now open your terminal (in your workspace for example)
* create a new folder for the demo
* run npm commands:
  * `npm init -y`
  * `npm install --save ps-list
* create new file `index.js` with
```javascript
const psList = require('ps-list');

psList().then(data => {
	console.log(data);
});
```
* run the example with `node index.js`
* in your console should now stand something like 
```javascript
[
  { pid: 0, name: 'System Idle Process', cmd: 'System Idle Process' },
  { pid: 4, name: 'System', cmd: 'System' },
]
```

else you could also try `tasklist` in your terminal (which will be used in ps-list)

**Comment by chrishelgert** [comment]
@Koolstr have you tried it?

**Comment by Koolstr** [comment]
Haven't gotten around to it yet, sorry. I do intend to do it shortly though. Thanks for writing up the method.

**Comment by chrishelgert** [comment]
As it looks like a windows configuration problem and not problem with windows itself - i will close this issue.

**Comment by Koolstr** [comment]
Sorry, forgot to get back to this. I ran the ps-list usage example and it came back with a full list of my processes, so that narrows it down to fkill as being problematic.

I similarly did the usage test with fkill, and it did not work. Where do we go from here?
